version: "3.7"
services:

    server:
      image: node:latest
      ports:
        - "3009:3000"
      volumes:
        - .:/usr/src/app
      working_dir: /usr/src/app/server
      command: sh -c "npm install && npm start"
      depends_on:
        - mongodb

    mongodb:
      image: mongo:latest
      ports:
        - 27018:27017
      volumes:
        - mongodb-data:/data

volumes:
    mongodb-data:
    ollama_volume:

